#!/usr/bin/env sh
read -p 'Group Id: ' GROUP_ID
read -p 'Artifact Id: ' ARTIFACT_ID
mvn archetype:generate -DgroupId=${GROUP_ID} -DartifactId=${ARTIFACT_ID} -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false
