#!/bin/bash
docker run \
  --name docker_dns_proxy \
  --hostname dns.mageddo \
  --restart=unless-stopped \
  -p 5380:5380 \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -d \
  defreitas/dns-proxy-server
