#!/bin/bash
docker run \
  --name mysql-gendb \
  --hostname mysql-gendb \
  -e MYSQL_ROOT_PASSWORD=mysqlroot@ \
  -e MYSQL_USER=mysql \
  -e MYSQL_PASSWORD=example \
  -p 3307:3306 \
  -d \
  mysql:latest

