#!/bin/bash

docker run \
    --name rr_dev_mysql_server \
    -d \
    -p 3306:3306 \
    mysql/mysql-server

## NOTE ###
# After deploying the container, do the following initializing jobs:
# 1. Get the genetated root password: `docker logs mysql1 2>&1 | grep GENERATED`
# 2. Connect to the container in interactive mode with "mysql" and the genetated password: `docker exec -it mysql1 mysql -uroot -p`
# 3. Change the root password (Important!!! The genetated password will be invalid once used) `ALTER USER 'root'@'localhost' IDENTIFIED BY 'newpassword';` 
# 4. Add a new user for your application(Best practice: avoid using root account directly) `CREATE USER 'new_user_name'@'%' IDENTIFIED BY 'new_password';` 
