#!/bin/bash

## read password for the key store
while true; do
  read -p 'Enter key pass: ' -s KEY_PASS
  if [[ ! -z ${KEY_PASS} ]]; then
    echo 
    break;
  fi
  echo 
done

read -p 'Enter keystore file name [Default: jsk.jks]: ' OUTPUT_FILE 
[[ ! -z ${OUTPUT_FILE} ]] || OUTPUT_FILE='jsk.jks'

read -p 'Enter alias for the keystore [Default: scdemo-auth]: ' ALIAS
[[ ! -z ${ALIAS} ]] || ALIAS='scdemo-auth'

echo "output: ${OUTPUT_FILE}"
echo "alias: ${ALIAS}"
echo "keypass: ${KEY_PASS}"

keytool -genkeypair -alias ${ALIAS} -keyalg RSA -keypass ${KEY_PASS} -keystore ${OUTPUT_FILE} -storepass ${KEY_PASS} << EOF
unspecified unspecified
dev
roro
Vancouver
British Columbia
CA
yes
EOF
