#!/usr/bin/env sh

serverRoot=/home/${USER}/code/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository
launcherJar=$(ls ${serverRoot}/plugins/org.eclipse.equinox.launcher_*.jar)
lombokPath=/home/${USER}/jars/lombok.jar

java \
    -javaagent:${lombokPath} \
    -Xbootclasspath/p:${lombokPath} \
    -Declipse.application=org.eclipse.jdt.ls.core.id1 \
    -Dosgi.bundles.defaultStartLevel=4 \
    -Declipse.product=org.eclipse.jdt.ls.core.product \
    -Dlog.level=ALL \
    -noverify \
    -Xmx1G \
    -jar ${launcherJar} \
    -configuration ${serverRoot}/config_linux \
    -data /home/vagrant/workspace/ \
    "$@"
